# Generated by Django 5.1.4 on 2024-12-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="items",),
        migrations.AddField(
            model_name="cartitem",
            name="size_in_kg",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("turmeric", "Turmeric"),
                    ("chilly", "Chilly"),
                    ("coriander", "Coriander"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(
                choices=[
                    ("all_over_the_world", "All Over The World"),
                    ("only_in_india", "Only In India"),
                ],
                default="India",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="Accounts.cart",
            ),
        ),
        migrations.AlterField(
            model_name="item", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="stock",
            field=models.CharField(
                choices=[
                    ("coming_soon", "Coming Soon"),
                    ("in_stock", "In Stock"),
                    ("out_of_stock", "Out Of Stock"),
                ],
                max_length=20,
            ),
        ),
    ]
